server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: airports-service
  datasource:
    url: ${FLT_PREP_DB_URL}
    username: ${FLT_PREP_DB_UNAME}
    password: ${FLT_PREP_DB_PASS}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    deserialization:
      fail-on-unknown-properties: true

